config {
    type: "view",
    database: "data-prd-388914",
    schema: "analytics_curated",
    name: "shipments_xl_etas_customer_cod_external",
    bigquery: {
        labels: {
            department: "analytics",
            "name": "gods_eye"
        }
    },
    tags: ["once"]
}

SELECT
  -- COUNTER
  shipments.trackingId shipments_trackingId,
  -- counter
  shipments.option_metadata_LegacyTrackingId shipments_option_metadata_LegacyTrackingId,
  -- trackingid
  shipments.internalKey shipments_internalKey,
  -- receivedorderid
  shipments.master_children shipments_master_children,
  -- VERSION AND PLATFORM
  shipments.metadata_source shipments_metadata_source,
  -- DATES
  -- CREATED
  --shipments.createdAt_utc shipments_createdAt_utc,
  shipments.createdAt shipments_createdAt,
  -- DELIVERY TYPE AND PACKAGESIZE
  CASE
    WHEN shipments.origin_country IN ('MEX') AND customer.userid_value IN ('179762', '362') THEN 'Tailor Made MEX'
    ELSE shipments.deliveryType
END
  shipments_deliveryType,
  CASE
    WHEN shipments.origin_country IN ('CHL') AND xl.upgraded = FALSE AND (shipments.packageSize IS NULL OR shipments.packageSize IN ('')) THEN shipments.items_size
    WHEN shipments.origin_country IN ('CHL')
  AND xl.upgraded = FALSE THEN shipments.packageSize
    WHEN xl.legacy_packagesize <> xl.lts_packagesize THEN xl.lts_packagesize
    WHEN shipments.packageSize IS NULL
  OR shipments.packageSize IN ('') THEN shipments.items_size
    ELSE shipments.packageSize
END
  shipments_packageSize,
  -- ITEM
  --shipments.items_size shipments_items_size,
  shipments.items_weight shipments_items_weight,
  shipments.items_description shipments_items_description,
  -- Jorge, KAM
  -- PICKUP DETAILS
  --shipments.option_ecoTag shipments_option_ecoTag,
  shipments.option_pickUpAfter shipments_option_pickUpAfter,
  -- STATUS STATEMACHINE
  -- ATTEMPTS
  shipments.data_unsuccessfulPickupAttempts shipments_data_unsuccessfulPickupAttempts,
  shipments.data_pickupAttempts shipments_data_pickupAttempts,
  shipments.data_unsuccessfulDeliveryAttempts shipments_data_unsuccessfulDeliveryAttempts,
  shipments.data_deliveryAttempts shipments_data_deliveryAttempts,
  shipments.data_returnAttempts shipments_data_returnAttempts,
  --shipments.data_unsuccessfulReturnAttempts shipments_data_unsuccessfulReturnAttempts,
  -- COMPANY
  -- FULFILLMENT
  -- COD
  shipments.payment_cashOnDelivery_amount shipments_payment_cashOnDelivery_amount,
  shipments.payment_cashOnDelivery_driverHasPay shipments_payment_cashOnDelivery_driverHasPay,
  -- C2C
  shipments.c2c_category shipments_c2c_category,
  shipments.metadata_coverageStrategy shipments_metadata_coverageStrategy,
  -- ORIGIN
  shipments.origin_country shipments_origin_country,
  shipments.origin_geoType shipments_origin_geoType,
  --shipments.origin_lat shipments_origin_lat,
  --shipments.origin_lng shipments_origin_lng,
  CONCAT(shipments.origin_lat, ',', shipments.origin_lng) shipments_origin_lat_lng,
  --concat('http://maps.google.com/maps?z=12&t=m&q=loc:', shipments.origin_lat, ',', shipments.origin_lng) shipments_origin_lat_lng_url,
  --shipments.origin_locationId,
  CASE
    WHEN shipments.origin_station LIKE 'IX%' THEN 'IX'
    WHEN shipments.origin_station LIKE 'IV%' THEN 'IV'
    WHEN shipments.origin_station LIKE 'RM%' THEN 'RM'
    WHEN shipments.origin_station LIKE 'XVI%' THEN 'XVI'
    WHEN shipments.origin_station like'XV%' THEN 'XV'
    WHEN shipments.origin_station like'XIV%' THEN 'XIV'
    WHEN shipments.origin_station like'XIII%' THEN 'XIII'
    WHEN shipments.origin_station like'XII%' THEN 'XII'
    WHEN shipments.origin_station like'XI%' THEN 'XI'
    WHEN shipments.origin_station like'X%' THEN 'X'
    WHEN shipments.origin_station LIKE 'VIII%' THEN 'VIII'
    WHEN shipments.origin_station LIKE 'VII%' THEN 'VII'
    WHEN shipments.origin_station LIKE 'VI%' THEN 'VI'
    WHEN shipments.origin_station LIKE 'V%' THEN 'V'
    WHEN shipments.origin_station LIKE 'III%' THEN 'III'
    WHEN shipments.origin_station LIKE 'II%' THEN 'II'
    WHEN shipments.origin_station LIKE 'I%' THEN 'I'
    ELSE shipments.origin_station
END
  shipments_origin_station_chl,
  shipments.origin_station shipments_origin_station,
  --shipments.origin_type shipments_origin_type,
  shipments.origin_zipcode shipments_origin_zipcode,
  shipments.origin_zone shipments_origin_zone,
  shipments.origin_references shipments_origin_references,
  -- DESTINATION
  shipments.destination_geoType shipments_destination_geoType,
  --shipments.destination_lat shipments_destination_lat,
  --shipments.destination_lng shipments_destination_lng,
  CONCAT(shipments.destination_lat, ',', shipments.destination_lng) shipments_destination_lat_lng,
  --concat('http://maps.google.com/maps?z=12&t=m&q=loc:', shipments.destination_lat, ',', shipments.destination_lng) shipments_destination_lat_lng_url,
  --shipments.destination_locationId,
  CASE
    WHEN shipments.destination_station LIKE 'IX%' THEN 'IX'
    WHEN shipments.destination_station LIKE 'IV%' THEN 'IV'
    WHEN shipments.destination_station LIKE 'RM%' THEN 'RM'
    WHEN shipments.destination_station LIKE 'XVI%' THEN 'XVI'
    WHEN shipments.destination_station like'XV%' THEN 'XV'
    WHEN shipments.destination_station like'XIV%' THEN 'XIV'
    WHEN shipments.destination_station like'XIII%' THEN 'XIII'
    WHEN shipments.destination_station like'XII%' THEN 'XII'
    WHEN shipments.destination_station like'XI%' THEN 'XI'
    WHEN shipments.destination_station like'X%' THEN 'X'
    WHEN shipments.destination_station LIKE 'VIII%' THEN 'VIII'
    WHEN shipments.destination_station LIKE 'VII%' THEN 'VII'
    WHEN shipments.destination_station LIKE 'VI%' THEN 'VI'
    WHEN shipments.destination_station LIKE 'V%' THEN 'V'
    WHEN shipments.destination_station LIKE 'III%' THEN 'III'
    WHEN shipments.destination_station LIKE 'II%' THEN 'II'
    WHEN shipments.destination_station LIKE 'I%' THEN 'I'
    ELSE shipments.destination_station
END
  shipments_destination_station_chl,
  shipments.destination_station shipments_destination_station,
  --shipments.destination_type shipments_destination_type,
  shipments.destination_zipcode shipments_destination_zipcode,
  shipments.destination_zone shipments_destination_zone,
  -- PRICES
  shipments.prices_cost shipments_prices_cost,
  --shipments.prices_costExtraCityToCity shipments_prices_costExtraCityToCity,
  shipments.prices_costExtraInsurance shipments_prices_costExtraInsurance,
  -- SENDER
  CONCAT(COALESCE(shipments.sender_firstName, NULL), ' ', COALESCE(shipments.sender_lastName, NULL)) shipments_sender_firstName,
  --DATETIME(DATE(etas_v3.shipment_etas_eta_timestamp)) shipment_etas_eta_timestamp,
  CASE
    WHEN shipments.origin_country IN ('CHL') AND DATE(shipments.createdAt) < '2024-10-30' THEN DATETIME(DATE(etas_v3.shipment_etas_eta_timestamp))
    WHEN shipments.origin_country IN ('CHL')
  AND DATE(shipments.createdAt) >= '2024-10-30' THEN DATETIME(DATE(client_type))
    ELSE DATETIME(DATE(etas_v3.shipment_etas_eta_timestamp))
END
  shipment_etas_eta_timestamp,
  DATETIME(DATE(etas_v3.etas_client_eta_timestamp)) etas_client_eta_timestamp,
  -- ETAS (shipment_etas_v2)
  -- PICKUP_TYPE
  DATETIME(DATE(shipment_etas_v2.pickup_type)) shipment_etas_v2_pickup_type,
  shipment_etas_v2.evaluation_pickup_type shipment_etas_v2_evaluation_pickup_type,
  -- INBOUND_TYPE
  DATETIME(DATE(shipment_etas_v2.inbound_type)) shipment_etas_v2_inbound_type,
  shipment_etas_v2.evaluation_inbound_type shipment_etas_v2_evaluation_inbound_type,
  -- CLIENT_TYPE
  DATETIME(DATE(shipment_etas_v2.client_type)) shipment_etas_v2_client_type,
  shipment_etas_v2.evaluation_client_type shipment_etas_v2_evaluation_client_type,
  -- DISTRIBUTION_TYPE
  DATETIME(DATE(shipment_etas_v2.distribution_type)) shipment_etas_v2_distribution_type,
  shipment_etas_v2.evaluation_distribution_type shipment_etas_v2_evaluation_distribution_type,
  -- SUPPLY_TYPE
  DATETIME(DATE(shipment_etas_v2.supply_type)) shipment_etas_v2_supply_type,
  shipment_etas_v2.evaluation_supply_type shipment_etas_v2_evaluation_supply_type,
  -- CUSTOMER AND BILLING
  -- PROFILES AND CUSTOMER_CONFIG
  --customer.profiles_id,
  customer.auth_hydraclientid customer_auth_hydraclientid,
  --customer.auth_role customer_auth_role,
  --customer.auth_parentid customer_auth_parentid,
  customer.userid_value customer_userid_value,
  customer.details_createdat customer_details_createdat,
  --customer.details_updatedat,
  --customer.country_value,
  customer.details_company_name customer_details_company_name,
  customer.details_contact_email customer_details_contact_email,
  customer.details_payment_typestring customer_details_payment_typestring,
  -- XL
  xl.created_at xl_created_at,
  xl.dimensions_weight xl_dimensions_weight,
  xl.dimensions_length xl_dimensions_length,
  xl.dimensions_width xl_dimensions_width,
  xl.dimensions_height xl_dimensions_height,
  xl.dimensions_volumetric_weight xl_dimensions_volumetric_weight,
  xl.legacy_packagesize xl_legacy_packagesize,
  -- Tamaño inicial
  xl.lts_packagesize xl_lts_packagesize,
  -- Tamaño actualizado
  xl.resize xl_resize,
  xl.lts_price xl_lts_price,
  -- BUSINESS
  -- COD
  cod.orders_status cod_orders_status,
  DATE_SUB(cod.orders_deliveredAt, INTERVAL 6 hour) cod_orders_deliveredAt,
  cod.paymentMethod cod_paymentMethod,
  cod.referenceCode cod_referenceCode,
  cod.pago46PaymentId cod_pago46PaymentId,
  cod.paidAt cod_paidAt,
  cod.pendingAmount cod_pendingAmount,
  cod.amountPaid cod_amountPaid,
  cod.amount cod_amount,
  cod.orders_driverid cod_orders_driverid,
  cod.driverNickname cod_driverNickname,
  cod.driverName cod_driverName,
  cod.driverProvider cod_driverProvider,
  -- FULFILLMENT
  f.shipheroOrderNumber f_shipheroOrderNumber,
  -- EXTERNAL CARRIERS
  --external_orders.external_orders_id,
  external_orders.externalCarrierId external_orders_externalCarrierId,
  --external_orders.internalTracking external_orders_internalTracking,
  external_orders.externalTracking external_orders_externalTracking,
  -- TRACKING
  -- SHIPMENTS
  --FROM `data-prd-388914.data_mongo_views_prd.mongo_statemachine_shipments_json_id` shipments
FROM
  `data-prd-388914.data_mongo_enrinchment_views_prd.mongo_statemachine_shipments_json_id` shipments
  -- ETAS V3
LEFT JOIN (
  SELECT
    --COUNT(tracking_id), COUNT(DISTINCT tracking_id), COUNT(tracking_id) - COUNT(DISTINCT tracking_id)
    tracking_id,
    shipment_etas_eta_timestamp,
    etas_client_eta_timestamp
  FROM (
    SELECT
      tracking_id,
      MAX(CASE
          WHEN rule_type NOT IN ('CLIENT') THEN eta_timestamp
      END
        ) OVER (PARTITION BY tracking_id) shipment_etas_eta_timestamp,
      MAX(CASE
          WHEN rule_type IN ('CLIENT') THEN eta_timestamp
      END
        ) OVER (PARTITION BY tracking_id) etas_client_eta_timestamp,
      ROW_NUMBER() OVER (PARTITION BY tracking_id ORDER BY updated_at DESC ) order_updated_at
    FROM
      --`data-prd-388914.data_mongo_views_prd.mongo_etasprod_shipment_etas_json_id_RET`
      `data-prd-388914.data_mongo_enrinchment_views_prd.mongo_etasprod_shipment_etas_json_id` )
  WHERE
    order_updated_at = 1 ) etas_v3
ON
  shipments.trackingId = etas_v3.tracking_id
  -- ETAS (shipment_etas_v2)
LEFT JOIN (
  SELECT
    tracking_id,
    pickup_type_eta pickup_type,
    pickup_type_evaluation_successfully evaluation_pickup_type,
    inbound_type_eta inbound_type,
    inbound_type_evaluation_successfully evaluation_inbound_type,
    client_type_eta client_type,
    client_type_evaluation_successfully evaluation_client_type,
    distribution_type_eta distribution_type,
    distribution_type_evaluation_successfully evaluation_distribution_type,
    supply_type_eta supply_type,
    supply_type_evaluation_successfully evaluation_supply_type
  FROM
    `data-prd-388914.mongo_testing.gods_eye_v1_analytics_etas_v2` ) shipment_etas_v2
ON
  shipments.trackingId = shipment_etas_v2.tracking_id
  -- CUSTOMER AND BILLING
  -- PROFILES
LEFT JOIN
  `data-prd-388914.mongodb_v3.v3_customerprofilesprod_profiles` customer
ON
  shipments.account_client_id = customer.auth_hydraclientid
  -- XL
  --LEFT JOIN `data-prd-388914.mongodb_v3.v3_xl_events` xl on shipments.trackingId = xl.counter
LEFT JOIN (
  SELECT
    *
  FROM (
    SELECT
      counter,
      created_at,
      dimensions_weight,
      dimensions_length,
      dimensions_width,
      dimensions_height,
      dimensions_volumetric_weight,
      upgraded,
      legacy_packagesize,
      lts_packagesize,
      resize,
      lts_price,
      ROW_NUMBER() OVER (PARTITION BY counter ORDER BY upgraded_at DESC) AS order_updated_at
    FROM
      `data-prd-388914.mongodb_v3.v3_xl_events` )
  WHERE
    order_updated_at = 1 ) xl
ON
  shipments.trackingId = xl.counter
  -- COD
LEFT JOIN
  `data-prd-388914.mongodb_v3.v3_DbCODService_orders_referencedpayments` cod
ON
  shipments.trackingId = cod.orders_counter
  -- FULFILLMENT
LEFT JOIN
  `data-prd-388914.mongodb_v3.v3_fulfill99production_orders` f
ON
  shipments.trackingId = f.trackingNumber
  -- EXTERNAL CARRIERS
LEFT JOIN
  `data-prd-388914.mongodb_v3.v3_intrexternalcarriersprod_external_orders` external_orders
ON
  shipments.trackingId = external_orders.internalTracking
WHERE
  ( (EXTRACT(year
      FROM
        shipments.createdAt)) = EXTRACT(year
    FROM
      CURRENT_DATE('America/Mexico_City'))
    OR (EXTRACT(year
      FROM
        shipments.updatedAt)) = EXTRACT(year
    FROM
      CURRENT_DATE('America/Mexico_City')) )
